#LETTERS  "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
ROTOR_1 = "DMTWSILRUYQNKFEJCAZBPGXOHV"
ROTOR_2 = "HQZGPJTMOBLNCIFDYAWVEUSRKX"
ROTOR_3 = "UQNTLSZFMREHDPXKIBVYGJCWOA"

#LETTERS    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
REFLECTOR = "YRUHQSLDPXNGOKMIEBFZCWVJAT"